name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tag push (e.g., v0.1.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      # Install build and upload tools
      - name: Install dependencies
        run: pip install setuptools wheel twine

      # Build the package
      - name: Build package
        run: python setup.py sdist bdist_wheel

      # Upload to PyPI
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
